# Generated by Django 5.0.4 on 2024-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='название')),
                ('anons', models.CharField(max_length=120, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Staty')),
                ('date', models.DateTimeField(verbose_name='Data')),
            ],
        ),
    ]
