# Generated by Django 5.0.4 on 2024-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
    ]
